# Intel MIC Platform Software Stack (MPSS)
# Copyright (c) 2016, Intel Corporation.
#
# This program is free software; you can redistribute it and/or modify it
# under the terms and conditions of the GNU General Public License,
# version 2, as published by the Free Software Foundation.
#
# This program is distributed in the hope it will be useful, but WITHOUT
# ANY WARRANTY; without even the implied warranty of MERCHANTABILITY or
# FITNESS FOR A PARTICULAR PURPOSE.  See the GNU General Public License for
# more details.

# Makefile - Intel MIC x200 Linux driver.

mic_x200-y := mic_alut.o
mic_x200-y += mic_boot.o
mic_x200-y += mic_debugfs.o
mic_x200-y += mic_dmi_scan.o
mic_x200-y += mic_hw.o
mic_x200-y += mic_intr.o
mic_x200-y += mic_main.o
mic_x200-y += mic_sysfs.o

obj-$(CONFIG_INTEL_MIC_X200) += mic_x200.o
