# Intel MIC Platform Software Stack (MPSS)
# Copyright (c) 2016, Intel Corporation.
#
# This program is free software; you can redistribute it and/or modify it
# under the terms and conditions of the GNU General Public License,
# version 2, as published by the Free Software Foundation.
#
# This program is distributed in the hope it will be useful, but WITHOUT
# ANY WARRANTY; without even the implied warranty of MERCHANTABILITY or
# FITNESS FOR A PARTICULAR PURPOSE.  See the GNU General Public License for
# more details.

# Makefile - Intel MIC Coprocessor State Management (COSM) Driver

mic_cosm-y := cosm_main.o
mic_cosm-y += cosm_scif_server.o
mic_cosm-y += cosm_sysfs.o

obj-$(CONFIG_MIC_COSM) += mic_cosm.o
