# Intel MIC Platform Software Stack (MPSS)
# Copyright (c) 2016, Intel Corporation.
#
# This program is free software; you can redistribute it and/or modify it
# under the terms and conditions of the GNU General Public License,
# version 2, as published by the Free Software Foundation.
#
# This program is distributed in the hope it will be useful, but WITHOUT
# ANY WARRANTY; without even the implied warranty of MERCHANTABILITY or
# FITNESS FOR A PARTICULAR PURPOSE.  See the GNU General Public License for
# more details.

# Makefile - Intel MIC Linux driver.

obj-$(CONFIG_INTEL_MIC) += bus/
obj-$(CONFIG_INTEL_MIC_X100) += host/
obj-$(CONFIG_INTEL_MIC_X100) += card/
obj-$(CONFIG_INTEL_MIC_X200) += mic_x200/
obj-$(CONFIG_SCIF) += scif/
obj-$(CONFIG_MIC_COSM) += cosm/
obj-$(CONFIG_MIC_COSM_CLIENT) += cosm_client/
obj-m += vop/
